"""Structured per-request trace logging.

Sprint 41's ("Structured observability") dependency-free half: no
observability vendor, just one structured JSON log line per request,
correlated with `apps/web`'s own log line for the same call via
ADR-004's `X-Internal-Request-Id` header -- already generated by
`apps/web/lib/internal-api-client.ts` for every signed request, so this
middleware reads it rather than inventing a second correlation scheme.
The same header name is `app.api.internal_auth`'s private
`_HEADER_REQUEST_ID`; re-declared here (not imported) since this module
has no other reason to depend on that one's internals, and the string
itself is the ADR-004 wire contract, not an internal_auth-owned detail.

"Safe context" means exactly what gets logged and nothing more:
`request_id`, `method`, `path` (no query string, no headers, no body --
none of a request's actual content, so nothing here can ever be
sensitive, matching the product contract's Integrity/security posture),
plus `status_code` and `duration_ms` -- the two other fields sprint
41's acceptance bar names as worth having on one request's trace line.
This fires for every request regardless of whether ADR-004 auth
succeeds (an unsigned or unauthenticated request still gets a trace
line, at whatever status code it failed with), since Starlette
middleware wraps the whole call, not just the route handlers behind
`Depends(require_internal_signature)`.

Deliberately not attempted here: propagating this trace into the
per-provider log lines already scattered across
`app.providers.{nws,noaa_coops,stations}` (each its own bare
`logging.getLogger(__name__).warning(...)`, no request context) --
correlating *those* would need passing the request id down through
every provider call, a larger refactor than one sprint's dependency-free
increment should invent without evidence of it being worth the churn.
"""

from __future__ import annotations

import json
import logging
import sys
import time
import uuid
from collections.abc import Awaitable, Callable

from starlette.requests import Request
from starlette.responses import Response

logger = logging.getLogger("app.request")
logger.setLevel(logging.INFO)
# uvicorn's own logging.config.dictConfig only wires up handlers for the
# "uvicorn"/"uvicorn.access"/"uvicorn.error" loggers -- it never touches
# the root logger or gives one to arbitrary app loggers, and nothing
# else in this app calls logging.basicConfig(). Without a handler of its
# own, every logger.info() call below is silently dropped under a real
# `uvicorn app.main:app` run: no error, no output, nothing -- caught
# only because a real running server was checked, not just
# tests/test_request_logging.py's pytest `caplog` fixture, which
# installs its own handler on the root logger regardless of this
# logger's configuration and so happily passed while runtime output was
# empty. Deliberately leaving `propagate` at its default `True` (not
# `False`) so both this handler's real stdout output *and* caplog's
# root-level capture in tests keep working -- this app has nothing else
# attached to root, so propagating doesn't risk a second real copy of
# the line in production, only in the test fixture that wants it.
if not logger.handlers:
    _handler = logging.StreamHandler(sys.stdout)
    _handler.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(_handler)

_HEADER_REQUEST_ID = "X-Internal-Request-Id"


async def log_requests(
    request: Request, call_next: Callable[[Request], Awaitable[Response]]
) -> Response:
    """Starlette HTTP middleware: one structured JSON log line per
    request, and the same `request_id` echoed back on the response so a
    caller (or a browser's network tab) can see the exact id its own
    log line should be correlated against.
    """
    request_id = request.headers.get(_HEADER_REQUEST_ID) or str(uuid.uuid4())
    started = time.perf_counter()
    response = await call_next(request)
    duration_ms = round((time.perf_counter() - started) * 1000, 1)

    logger.info(
        json.dumps(
            {
                "request_id": request_id,
                "method": request.method,
                "path": request.url.path,
                "status_code": response.status_code,
                "duration_ms": duration_ms,
            }
        )
    )
    response.headers[_HEADER_REQUEST_ID] = request_id
    return response
