"""add forecast_cache table

Revision ID: 29a4918be459
Revises: ecef7818bd1f
Create Date: 2026-08-10 16:17:41.000765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a4918be459'
down_revision: Union[str, None] = 'ecef7818bd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_cache',
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['saved_locations.id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_cache')
    # ### end Alembic commands ###
