"""add passkey tables

Revision ID: e7c724d11d95
Revises: 29a4918be459
Create Date: 2026-08-10 16:39:08.605723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c724d11d95'
down_revision: Union[str, None] = '29a4918be459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passkey_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkey_credentials_credential_id'), 'passkey_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_passkey_credentials_user_id'), 'passkey_credentials', ['user_id'], unique=False)
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challenge', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_challenges_challenge'), 'webauthn_challenges', ['challenge'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_challenges_challenge'), table_name='webauthn_challenges')
    op.drop_table('webauthn_challenges')
    op.drop_index(op.f('ix_passkey_credentials_user_id'), table_name='passkey_credentials')
    op.drop_index(op.f('ix_passkey_credentials_credential_id'), table_name='passkey_credentials')
    op.drop_table('passkey_credentials')
    # ### end Alembic commands ###
