"""Location resolution (sprint 19).

Ports the curated-location dataset and dynamic (any-coordinate) location
resolution from the legacy `locations.py`, behind typed contracts and
sprint 17/18's station-catalog and coastal-validation building blocks.
Per docs/R1_RECONCILIATION_AUDIT.md, this is an adapt, not a verbatim
carry-over — except for the data itself.

**The two static datasets are a documented mechanical move, not a
hand-transcription.** `app/data/coastal_locations.json` (101 curated
spots) and `app/data/water_temps.json` (19 regional monthly
water-temperature profiles) were generated by `ast.literal_eval`-parsing
the legacy `locations.py`'s `COASTAL_LOCATIONS` and `_WATER_TEMPS`
literals directly, not retyped by hand — the values are guaranteed
byte-for-byte faithful to the source, which hand-transcription of ~1,500
lines of coordinates and station IDs could not credibly promise. The
legacy module's `COASTAL_LIVE_CAMS` dataset and `_FALLBACK_CONDITIONS`
(wind/wave fallback ranges) are unrelated to location resolution and are
not ported here.

Design, mirroring sprint 17/18's decoupling of data/fetch from pure
logic:

- `load_curated_locations`/`load_water_temp_profiles` read the two JSON
  files and validate them into typed models, cached for the process
  lifetime (`functools.lru_cache`) since they're static — the legacy
  module's equivalent optimization on `all_locations_sorted`.
- `find_nearest_locations`, `timezone_for_point`,
  `monthly_water_temps_for_region`, `format_dynamic_id`/
  `parse_dynamic_id`, and `resolve_dynamic_location` are pure functions
  over already-loaded data — no hidden I/O, easy to golden-test.
- `resolve_dynamic_location` is the direct port of the legacy
  `_resolve_dynamic_location`/`build_dynamic_location`. It takes
  pre-fetched CO-OPS/NDBC catalogs (sprint 17) as parameters rather than
  fetching them itself, matching the pattern established there.
  `parse_dynamic_id`'s range check reuses sprint 18's
  `is_valid_coordinate` instead of duplicating it.

`resolve_dynamic_location` is a strict subset of the legacy function's
inputs in one respect: like sprint 18's `gate_coastal_point`, it has no
extra behavior beyond what curated locations, CO-OPS, and NDBC data
provide — there's nothing else in the legacy version to defer, unlike
sprints 13-15's provider adapters.
"""

from __future__ import annotations

import json
import math
from functools import lru_cache
from pathlib import Path

from pydantic import BaseModel

from app.providers.coastal_bounds import is_valid_coordinate
from app.providers.stations import (
    CoopsStationCatalogEntry,
    NdbcStationCatalogEntry,
    nearest_coops_station,
    nearest_ndbc_stations,
)

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_COASTAL_LOCATIONS_PATH = _DATA_DIR / "coastal_locations.json"
_WATER_TEMPS_PATH = _DATA_DIR / "water_temps.json"

_DYNAMIC_ID_PREFIX = "pt_"
_DEFAULT_TEMP_REGION = "nc_south"
_DEFAULT_CONDITIONS_REGION = "atlantic_mid"
_DEFAULT_TIMEZONE = "America/New_York"
_NWS_ZONE_INHERIT_MILES = 75.0

# IANA timezone by coastal state. Every US coastal state is single-timezone
# except Florida, whose panhandle (west of the Apalachicola River, ~85°W) is
# Central while the rest is Eastern.
_STATE_TIMEZONE: dict[str, str] = {
    "ME": "America/New_York",
    "NH": "America/New_York",
    "MA": "America/New_York",
    "RI": "America/New_York",
    "CT": "America/New_York",
    "NY": "America/New_York",
    "NJ": "America/New_York",
    "DE": "America/New_York",
    "MD": "America/New_York",
    "VA": "America/New_York",
    "NC": "America/New_York",
    "SC": "America/New_York",
    "GA": "America/New_York",
    "AL": "America/Chicago",
    "MS": "America/Chicago",
    "LA": "America/Chicago",
    "TX": "America/Chicago",
    "CA": "America/Los_Angeles",
    "OR": "America/Los_Angeles",
    "WA": "America/Los_Angeles",
    "AK": "America/Anchorage",
    "HI": "Pacific/Honolulu",
}
_FL_TZ_BOUNDARY_LNG = -85.0


class CuratedLocation(BaseModel):
    id: str
    name: str
    state: str
    lat: float
    lng: float
    timezone: str
    coops_station: str
    ndbc_stations: list[str]
    nws_zone: str
    temp_region: str
    conditions_region: str
    temp_offset: int = 0


class NearestLocationMatch(BaseModel):
    location: CuratedLocation
    distance_miles: float


class ResolvedLocation(BaseModel):
    """A forecast-ready location — either a curated spot as-is, or an
    assembled dynamic point. `is_dynamic=False` means every field came
    directly from `CuratedLocation`; `is_dynamic=True` means station IDs
    were resolved from live catalogs and the coarse regional fields were
    inherited from the nearest curated neighbor (see
    `resolve_dynamic_location`).
    """

    id: str
    name: str
    state: str
    lat: float
    lng: float
    timezone: str
    coops_station: str
    water_temp_station: str
    ndbc_stations: list[str]
    nws_zone: str
    temp_region: str
    conditions_region: str
    temp_offset: int
    is_dynamic: bool


@lru_cache(maxsize=1)
def load_curated_locations() -> tuple[CuratedLocation, ...]:
    raw = json.loads(_COASTAL_LOCATIONS_PATH.read_text())
    return tuple(CuratedLocation.model_validate(entry) for entry in raw)


@lru_cache(maxsize=1)
def load_water_temp_profiles() -> dict[str, dict[int, float]]:
    raw = json.loads(_WATER_TEMPS_PATH.read_text())
    return {
        region: {int(month): temp for month, temp in months.items()}
        for region, months in raw.items()
    }


def _haversine_miles(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    earth_radius_miles = 3958.8
    dlat = math.radians(lat2 - lat1)
    dlng = math.radians(lng2 - lng1)
    a = (
        math.sin(dlat / 2) ** 2
        + math.cos(math.radians(lat1))
        * math.cos(math.radians(lat2))
        * math.sin(dlng / 2) ** 2
    )
    return earth_radius_miles * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def find_nearest_locations(
    lat: float,
    lng: float,
    locations: tuple[CuratedLocation, ...],
    n: int = 5,
    max_miles: float = 300.0,
) -> list[NearestLocationMatch]:
    """Nearest curated locations to `(lat, lng)` within `max_miles`,
    nearest-first, capped at `n`.
    """
    matches = [
        NearestLocationMatch(
            location=loc,
            distance_miles=round(_haversine_miles(lat, lng, loc.lat, loc.lng), 1),
        )
        for loc in locations
    ]
    matches = [m for m in matches if m.distance_miles <= max_miles]
    matches.sort(key=lambda m: m.distance_miles)
    return matches[:n]


def find_curated_location(
    location_id: str, locations: tuple[CuratedLocation, ...]
) -> CuratedLocation | None:
    """Look up a curated location by its stable id, or `None` if
    *location_id* isn't a curated id (it may be a dynamic `pt_` id, or
    simply unknown).
    """
    for loc in locations:
        if loc.id == location_id:
            return loc
    return None


def search_curated_locations(
    query: str, locations: tuple[CuratedLocation, ...], limit: int = 10
) -> list[CuratedLocation]:
    """Case-insensitive substring search over curated locations. Name
    matches rank before state/id matches; ties keep the dataset's
    original order. An empty or whitespace-only *query* returns `[]`
    rather than the whole dataset.
    """
    q = query.strip().lower()
    if not q:
        return []
    name_matches = [loc for loc in locations if q in loc.name.lower()]
    name_match_ids = {loc.id for loc in name_matches}
    other_matches = [
        loc
        for loc in locations
        if loc.id not in name_match_ids
        and (q in loc.state.lower() or q in loc.id.lower())
    ]
    return (name_matches + other_matches)[:limit]


def timezone_for_point(state: str, lng: float) -> str | None:
    """Best-effort IANA timezone for a US coastal point from its state.
    Returns `None` when the state is unknown so the caller can fall back
    to another source (e.g. the nearest curated location's timezone).
    """
    state = (state or "").upper()
    if state == "FL":
        return "America/Chicago" if lng < _FL_TZ_BOUNDARY_LNG else "America/New_York"
    return _STATE_TIMEZONE.get(state)


def monthly_water_temps_for_region(
    temp_region: str, temp_offset: int, profiles: dict[str, dict[int, float]]
) -> dict[int, float]:
    """Monthly water-temp averages for a region, with `temp_offset`
    applied. Falls back to `nc_south` for an unrecognized region.
    """
    base = profiles.get(temp_region) or profiles[_DEFAULT_TEMP_REGION]
    if not temp_offset:
        return dict(base)
    return {month: temp + temp_offset for month, temp in base.items()}


def format_dynamic_id(lat: float, lng: float) -> str:
    """Stateless location id encoding a coastal point, rounded to 3
    decimals (~110 m) — finer than the forecast's own spatial resolution
    but coarse enough that GPS jitter maps to the same id.
    """
    return f"{_DYNAMIC_ID_PREFIX}{lat:.3f}_{lng:.3f}"


def parse_dynamic_id(location_id: str) -> tuple[float, float] | None:
    """Decode `(lat, lng)` from a dynamic id, or `None` if it isn't one
    or the coordinates are out of range.
    """
    if not location_id or not location_id.startswith(_DYNAMIC_ID_PREFIX):
        return None
    body = location_id[len(_DYNAMIC_ID_PREFIX) :]
    # Longitude is negative across the US; split on the *last* underscore
    # to keep the minus sign attached to the longitude.
    parts = body.rsplit("_", 1)
    if len(parts) != 2:
        return None
    try:
        lat, lng = float(parts[0]), float(parts[1])
    except ValueError:
        return None
    if not is_valid_coordinate(lat, lng):
        return None
    return lat, lng


def resolve_dynamic_location(
    lat: float,
    lng: float,
    curated_locations: tuple[CuratedLocation, ...],
    coops_tide_stations: list[CoopsStationCatalogEntry],
    coops_watertemp_stations: list[CoopsStationCatalogEntry],
    ndbc_stations: list[NdbcStationCatalogEntry],
) -> tuple[ResolvedLocation, float]:
    """Assemble a dynamic location and report its nearest-anchor
    distance in miles (the smallest of: nearest curated location,
    nearest CO-OPS tide station, nearest NDBC buoy) — callers use this
    with `app.providers.coastal_bounds.gate_coastal_point`-style
    thresholds to decide whether the point is coastal enough to serve.
    """
    nearest_matches = find_nearest_locations(
        lat, lng, curated_locations, n=1, max_miles=1.0e9
    )
    nearest = nearest_matches[0] if nearest_matches else None
    nearest_miles = nearest.distance_miles if nearest else float("inf")

    coops = nearest_coops_station(coops_tide_stations, lat, lng)
    ndbc = nearest_ndbc_stations(ndbc_stations, lat, lng, n=2)
    watertemp = nearest_coops_station(coops_watertemp_stations, lat, lng)

    coops_id = (
        coops.id if coops else (nearest.location.coops_station if nearest else "")
    )
    water_temp_station = watertemp.id if watertemp else (coops_id or "")
    ndbc_ids = (
        [s.id for s in ndbc]
        if ndbc
        else (list(nearest.location.ndbc_stations) if nearest else [])
    )

    state = coops.state if coops else (nearest.location.state if nearest else "")

    conditions_region = (
        nearest.location.conditions_region if nearest else _DEFAULT_CONDITIONS_REGION
    )
    temp_region = nearest.location.temp_region if nearest else _DEFAULT_TEMP_REGION
    temp_offset = nearest.location.temp_offset if nearest else 0

    timezone = timezone_for_point(state, lng) or (
        nearest.location.timezone if nearest else _DEFAULT_TIMEZONE
    )

    nws_zone = ""
    if nearest and nearest_miles <= _NWS_ZONE_INHERIT_MILES:
        nws_zone = nearest.location.nws_zone

    name = (
        f"Near {nearest.location.name}"
        if nearest and nearest_miles <= 25.0
        else f"Coastal spot ({lat:.2f}, {lng:.2f})"
    )

    anchor_candidates = [nearest_miles]
    if coops:
        anchor_candidates.append(coops.distance_miles)
    if ndbc:
        anchor_candidates.append(ndbc[0].distance_miles)
    anchor_miles = min(anchor_candidates)

    location = ResolvedLocation(
        id=format_dynamic_id(lat, lng),
        name=name,
        state=state,
        lat=lat,
        lng=lng,
        timezone=timezone,
        coops_station=coops_id,
        water_temp_station=water_temp_station,
        ndbc_stations=ndbc_ids,
        nws_zone=nws_zone,
        temp_region=temp_region,
        conditions_region=conditions_region,
        temp_offset=temp_offset,
        is_dynamic=True,
    )
    return location, anchor_miles


def resolved_from_curated(location: CuratedLocation) -> ResolvedLocation:
    """Adapt a curated location to the same `ResolvedLocation` shape a
    dynamic point resolves to, so callers only need one result type.
    """
    return ResolvedLocation(
        id=location.id,
        name=location.name,
        state=location.state,
        lat=location.lat,
        lng=location.lng,
        timezone=location.timezone,
        coops_station=location.coops_station,
        water_temp_station=location.coops_station,
        ndbc_stations=list(location.ndbc_stations),
        nws_zone=location.nws_zone,
        temp_region=location.temp_region,
        conditions_region=location.conditions_region,
        temp_offset=location.temp_offset,
        is_dynamic=False,
    )
